-- Run this once in the shared class Supabase project's SQL editor.

create table if not exists public.class_registrations (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  whatsapp text not null,
  email text,
  reason text not null,
  reason_category text not null default 'Other',
  mentorship_interest text not null default 'Not answered',
  receipt_path text not null,
  receipt_name text not null,
  receipt_size integer not null,
  receipt_hash text,
  fraud_score integer not null default 0,
  fraud_status text not null default 'review',
  fraud_checks jsonb not null default '{}'::jsonb,
  payment_status text not null default 'pending',
  student_access_code text,
  approved_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.class_registrations add column if not exists receipt_hash text;
alter table public.class_registrations add column if not exists fraud_score integer not null default 0;
alter table public.class_registrations add column if not exists fraud_status text not null default 'review';
alter table public.class_registrations add column if not exists fraud_checks jsonb not null default '{}'::jsonb;
alter table public.class_registrations add column if not exists student_access_code text;
alter table public.class_registrations add column if not exists approved_at timestamptz;

alter table public.class_registrations enable row level security;

drop policy if exists "Anyone can submit a class registration" on public.class_registrations;
create policy "Anyone can submit a class registration"
on public.class_registrations for insert
to anon, authenticated
with check (
  char_length(full_name) between 3 and 120
  and char_length(whatsapp) between 10 and 20
  and char_length(reason) between 20 and 2000
  and receipt_size > 0
  and receipt_size <= 10485760
  and char_length(receipt_hash) = 64
  and fraud_score between 0 and 100
  and fraud_status in ('passed', 'review')
  and payment_status = 'pending'
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('class-receipts', 'class-receipts', false, 10485760, array['application/pdf', 'image/jpeg', 'image/png', 'image/heic', 'image/heif', 'image/webp'])
on conflict (id) do update set
  public = false,
  file_size_limit = 10485760,
  allowed_mime_types = array['application/pdf', 'image/jpeg', 'image/png', 'image/heic', 'image/heif', 'image/webp'];

drop policy if exists "Anyone can upload a class receipt PDF" on storage.objects;
drop policy if exists "Anyone can upload a class receipt file" on storage.objects;
create policy "Anyone can upload a class receipt file"
on storage.objects for insert
to anon, authenticated
with check (
  bucket_id = 'class-receipts'
  and (storage.foldername(name))[1] = 'receipts'
  and lower(storage.extension(name)) in ('pdf', 'jpg', 'jpeg', 'png', 'heic', 'heif', 'webp')
);

create index if not exists class_registrations_created_at_idx
on public.class_registrations (created_at desc);

create index if not exists class_registrations_category_idx
on public.class_registrations (reason_category);

create unique index if not exists class_registrations_receipt_hash_idx
on public.class_registrations (receipt_hash)
where receipt_hash is not null;

create table if not exists public.class_lessons (
  id bigint generated by default as identity primary key,
  lesson_number integer not null unique,
  title text not null,
  summary text not null,
  assignment_title text not null,
  assignment_prompt text not null,
  submission_type text not null default 'commit',
  deadline_days integer not null default 7,
  video_url text,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.class_submissions (
  id uuid primary key default gen_random_uuid(),
  registration_id uuid not null references public.class_registrations(id) on delete cascade,
  lesson_id bigint not null references public.class_lessons(id) on delete cascade,
  repository_url text,
  commit_url text,
  notes text,
  status text not null default 'pending',
  feedback text,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  unique (registration_id, lesson_id)
);

alter table public.class_lessons enable row level security;
alter table public.class_submissions enable row level security;

insert into public.class_lessons
  (lesson_number, title, summary, assignment_title, assignment_prompt, submission_type, deadline_days)
values
  (1, 'Plan and scaffold the product', 'Turn one idea into a clear product structure before designing screens or generating features.', 'Create the project foundation', 'Create a GitHub repository containing the folders, README, product goal, intended user, main pages and planned features for the product you will improve throughout the class.', 'repository', 3),
  (2, 'Build a clear interface', 'Apply visual hierarchy, spacing, typography, colour, responsiveness and accessibility without decorating away the product’s purpose.', 'Upgrade the scaffold with a complete UI', 'Build the main screens, follow the UI rules from the lesson and submit the final GitHub commit that shows the responsive interface.', 'commit', 7),
  (3, 'Connect the frontend journey', 'Turn separate screens into one usable flow with navigation, forms, feedback, loading states and useful empty states.', 'Complete the main user flow', 'Connect the pages and interactions required for the main user journey, test them on mobile and submit the final commit.', 'commit', 7),
  (4, 'Add Supabase and backend logic', 'Design the data, authentication, storage and permissions required to make the product remember and protect information.', 'Make the product store real data', 'Connect Supabase, create the required schema and policies, replace sample data with working data and submit the final commit.', 'commit', 7),
  (5, 'Test errors, permissions and edge cases', 'Review the product beyond its homepage and protect the journeys that can fail, leak data or confuse users.', 'Complete a product quality pass', 'Test validation, loading, empty, error, mobile and permission states. Fix the problems you find and submit the final commit with your testing notes.', 'commit', 5),
  (6, 'Deploy and present the finished product', 'Prepare a clean production build, deployment, documentation and demonstration that another person can understand.', 'Ship the completed product', 'Deploy the product, update the README with setup instructions and submit the final GitHub commit plus the repository link.', 'commit', 7)
on conflict (lesson_number) do update set
  title = excluded.title,
  summary = excluded.summary,
  assignment_title = excluded.assignment_title,
  assignment_prompt = excluded.assignment_prompt,
  submission_type = excluded.submission_type,
  deadline_days = excluded.deadline_days;

create or replace function public.get_student_classroom(p_whatsapp text, p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_registration public.class_registrations;
  v_lessons jsonb;
begin
  select * into v_registration
  from public.class_registrations
  where right(regexp_replace(whatsapp, '[^0-9]', '', 'g'), 10) = right(regexp_replace(p_whatsapp, '[^0-9]', '', 'g'), 10)
    and upper(student_access_code) = upper(trim(p_code))
    and payment_status = 'confirmed'
  limit 1;

  if v_registration.id is null then
    raise exception 'ACCESS_DENIED';
  end if;

  select coalesce(jsonb_agg(lesson_data order by lesson_number), '[]'::jsonb)
  into v_lessons
  from (
    select
      l.lesson_number,
      jsonb_build_object(
        'id', l.id,
        'lessonNumber', l.lesson_number,
        'title', l.title,
        'summary', l.summary,
        'assignmentTitle', l.assignment_title,
        'assignmentPrompt', l.assignment_prompt,
        'submissionType', l.submission_type,
        'deadlineDays', l.deadline_days,
        'videoUrl', l.video_url,
        'locked', case
          when l.lesson_number = 1 then false
          else not exists (
            select 1 from public.class_submissions previous_submission
            join public.class_lessons previous_lesson on previous_lesson.id = previous_submission.lesson_id
            where previous_submission.registration_id = v_registration.id
              and previous_lesson.lesson_number = l.lesson_number - 1
              and previous_submission.status = 'passed'
          )
        end,
        'submission', (
          select jsonb_build_object(
            'id', s.id,
            'repositoryUrl', s.repository_url,
            'commitUrl', s.commit_url,
            'notes', s.notes,
            'status', s.status,
            'feedback', s.feedback,
            'submittedAt', s.submitted_at,
            'reviewedAt', s.reviewed_at
          )
          from public.class_submissions s
          where s.registration_id = v_registration.id and s.lesson_id = l.id
        )
      ) as lesson_data
    from public.class_lessons l
    where l.is_published = true
  ) lessons;

  return jsonb_build_object(
    'student', jsonb_build_object('id', v_registration.id, 'name', v_registration.full_name),
    'classStarts', '2026-10-01',
    'lessons', v_lessons
  );
end;
$$;

create or replace function public.submit_class_assignment(
  p_whatsapp text,
  p_code text,
  p_lesson_id bigint,
  p_repository_url text,
  p_commit_url text,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_registration public.class_registrations;
  v_lesson public.class_lessons;
begin
  select * into v_registration
  from public.class_registrations
  where right(regexp_replace(whatsapp, '[^0-9]', '', 'g'), 10) = right(regexp_replace(p_whatsapp, '[^0-9]', '', 'g'), 10)
    and upper(student_access_code) = upper(trim(p_code))
    and payment_status = 'confirmed'
  limit 1;

  if v_registration.id is null then raise exception 'ACCESS_DENIED'; end if;

  select * into v_lesson from public.class_lessons where id = p_lesson_id and is_published = true;
  if v_lesson.id is null then raise exception 'LESSON_NOT_FOUND'; end if;

  if v_lesson.lesson_number > 1 and not exists (
    select 1 from public.class_submissions s
    join public.class_lessons l on l.id = s.lesson_id
    where s.registration_id = v_registration.id
      and l.lesson_number = v_lesson.lesson_number - 1
      and s.status = 'passed'
  ) then raise exception 'LESSON_LOCKED'; end if;

  if p_repository_url is null or p_repository_url !~* '^https://github[.]com/' then
    raise exception 'VALID_GITHUB_REPOSITORY_REQUIRED';
  end if;
  if v_lesson.submission_type = 'commit' and (p_commit_url is null or p_commit_url !~* '^https://github[.]com/.+/commit/[a-f0-9]+') then
    raise exception 'VALID_GITHUB_COMMIT_REQUIRED';
  end if;

  insert into public.class_submissions
    (registration_id, lesson_id, repository_url, commit_url, notes, status, feedback, submitted_at, reviewed_at)
  values
    (v_registration.id, v_lesson.id, trim(p_repository_url), nullif(trim(p_commit_url), ''), nullif(trim(p_notes), ''), 'pending', null, now(), null)
  on conflict (registration_id, lesson_id) do update set
    repository_url = excluded.repository_url,
    commit_url = excluded.commit_url,
    notes = excluded.notes,
    status = 'pending',
    feedback = null,
    submitted_at = now(),
    reviewed_at = null
  where public.class_submissions.status <> 'passed';

  return public.get_student_classroom(p_whatsapp, p_code);
end;
$$;

revoke all on function public.get_student_classroom(text, text) from public;
revoke all on function public.submit_class_assignment(text, text, bigint, text, text, text) from public;
grant execute on function public.get_student_classroom(text, text) to anon, authenticated;
grant execute on function public.submit_class_assignment(text, text, bigint, text, text, text) to anon, authenticated;
